export default {
    products: [
        {
            _id: '1',
            name: ' Running Shirt ',
            category: 'Shirts',
            image: '/front-end/img/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike hoddie',
            category: 'Hoddie',
            image: '/front-end/img/product-2.jpg',
            price: 80,
            brand: 'Hiskywin',
            rating: 5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'nike jacket',
            category: 'jacket',
            image: '/front-end/img/product-3.jpg',
            price: 200,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'sweater',
            category: 'Shirts',
            image: '/front-end/img/product-4.jpg',
            price: 45,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'nike tank',
            category: 'tank',
            image: '/front-end/img/product-5.jpg',
            price: 22,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};